# Generated by Django 2.2.7 on 2019-11-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=False, max_length=254, unique=True, verbose_name='email'),
        ),
    ]
